service: punkapi-api
plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-domain-manager
 
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  endpointType: REGIONAL
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:*
      Resource: !Join
        - ""
        - - !GetAtt FavoritesTable.Arn
          - "*"
package:
  exclude:
    - node_modules/**

functions:
  getAllFavorites:
    handler: handlers.getAll
    events:
      - http: GET /
  createFavorite:
    handler: handlers.create
    events:
      - http: POST /{id}
  removeFavorite:
    handler: handlers.remove
    events:
      - http: DELETE /{id}
          
custom:
  serverless-offline:
   port: 4000
  customDomain:
    domainName: "favorite.${env:DOMAIN}"
    certificateName: "*.${env:DOMAIN}"
    createRoute53Record: true
    endpointType: "regional"
  dynamodb:
    stages:
      - dev
    start:
      port: 8800
      inMemory: true
      migrate: true
      seed: true
      convertEmptyValues: true

resources:
  Resources:
    FavoritesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: punkapi-favorites
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST